INSERT INTO techblog_db.user (id, username, email, password) VALUES ( '1',  'Shagomir', 'm.j.knudson@gmail.com', '$2b$10$AUSai4ho.HBQt.IkpS9OtuRPdZGVsOmk2oqkp96ofaw//W6kxj7lS');

INSERT INTO techblog_db.post (id, post_title, post_text, created_at, updated_at, author_id) VALUES ('1', 'Test Post', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2013-03-13 00:00:00', '2013-03-13 00:00:00', '1');
INSERT INTO techblog_db.post (id, post_title, post_text, created_at, updated_at, author_id)  VALUES ('2', 'Second Post', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.','2013-03-13 00:00:00', '2013-03-13 00:00:00', '1');
INSERT INTO techblog_db.post (id, post_title, post_text, created_at, updated_at, author_id) VALUES ('3', 'Third Post', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2013-03-13 00:00:00', '2013-03-13 00:00:00', '1');

INSERT INTO techblog_db.comment (id, comment_text, created_at, updated_at, commentor_id, post_id) VALUES ('1', 'Test Comment', '2013-03-14 00:00:00', '2013-03-14 00:00:00', '1', '1');
INSERT INTO techblog_db.comment (id, comment_text, created_at, updated_at, commentor_id, post_id) VALUES ('2', 'Test Comment 2', '2013-03-14 00:00:00', '2013-03-14 00:00:00', '1', '1');
INSERT INTO techblog_db.comment (id, comment_text, created_at, updated_at, commentor_id, post_id) VALUES ('3', 'Test Comment 3', '2013-03-14 00:00:00', '2013-03-14 00:00:00', '1', '1');
INSERT INTO techblog_db.comment (id, comment_text, created_at, updated_at, commentor_id, post_id) VALUES ('4', 'Test Comment 4', '2013-03-14 00:00:00', '2013-03-14 00:00:00', '1', '2');
INSERT INTO techblog_db.comment (id, comment_text, created_at, updated_at, commentor_id, post_id) VALUES ('5', 'Test Comment 5', '2013-03-14 00:00:00', '2013-03-14 00:00:00', '1', '2');
INSERT INTO techblog_db.comment (id, comment_text, created_at, updated_at, commentor_id, post_id) VALUES ('6', 'Test Comment 6', '2013-03-14 00:00:00', '2013-03-14 00:00:00', '1', '3');